### ISSUE TITLE
FileNotFoundError: HITRAN HCl line list is missing?

### ISSUE THREAD

**Issue by TieDyeAstronomer** [ExoMol/exomol.com#22]
I've run into a FileNotFoundError exception when attempting to generate a cross section for HCl. Any help or insights will be greatly appreciated!

## Info to reproduce
Here's the webpage in question: https://www.exomol.com/xsec/1H-35Cl/

And here is an example set of parameters which I've used:

```
Δν = 0.01
νmin = 0
νmax = 17999
T = 300
Two-column output: ν and σ: True
```

(I've attempted varying each parameter, but always receive the same exception.)

## Traceback
```
Environment:


Request Method: POST
Request URL: https://www.exomol.com/xsec/1H-35Cl/

Django Version: 3.2.18
Python Version: 3.6.8
Installed Applications:
('mezzanine.boot',
 'theme_tori',
 'exomol_users',
 'django.contrib.messages',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.redirects',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.sitemaps',
 'mezzanine.conf',
 'mezzanine.core',
 'mezzanine.generic',
 'mezzanine.pages',
 'mezzanine.blog',
 'mezzanine.forms',
 'mezzanine.galleries',
 'mezzanine.accounts',
 'taggit',
 'chem',
 'refs',
 'data',
 'api',
 'xsec',
 'news',
 'conferences',
 'bibliography',
 'spectroscopic_model',
 'filebrowser_safe',
 'grappelli_safe',
 'django.contrib.admin',
 'django.contrib.staticfiles',
 'django_comments')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'mezzanine.core.request.CurrentRequestMiddleware',
 'mezzanine.core.middleware.RedirectFallbackMiddleware',
 'mezzanine.core.middleware.AdminLoginInterfaceSelectorMiddleware',
 'mezzanine.core.middleware.SitePermissionMiddleware',
 'mezzanine.pages.middleware.PageMiddleware')



Traceback (most recent call last):
  File "/mnt/data/exomol/exomol-env/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/mnt/data/exomol/exomol-env/lib64/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/data/exomol/exomol3/xsec/views.py", line 21, in isotopologue_xsec
    c.update(do_search(form))
  File "/mnt/data/exomol/exomol3/xsec/views.py", line 40, in do_search
    return get_xsec(xsec_meta, xnumin, xnumax, xT, xdnu, spoon_feed)
  File "/mnt/data/exomol/exomol3/xsec/xsec_utils.py", line 202, in get_xsec
    rnulo, rnuhi, rsigma = get_rsigma(xsec_meta, xT, xnumin, xnumax, xdnu)
  File "/mnt/data/exomol/exomol3/xsec/xsec_utils.py", line 166, in get_rsigma
    rnumin, rnumax, rdnu)
  File "/mnt/data/exomol/exomol3/xsec/xsec_utils.py", line 143, in get_sigma
    f = open(bsig_path, 'rb')

Exception Type: FileNotFoundError at /xsec/1H-35Cl/
Exception Value: [Errno 2] No such file or directory: '/mnt/data/exomol/exomol3_data/xsecs/1H-35Cl/1H-35Cl__HITRAN-HCl__0-18000__300K__0bar__0.01.bsig'

```

**Comment by Trovemaster** [comment]
It should be working now. Thanks a lot for reporting the problem.
